name: first

on: push

jobs:
    job1:
        name: First job
        runs-on: ubuntu-latest
        steps:
        - name: Step one - Check out code
          uses: actions/checkout@v2
        - name: Run ShellCheck
          uses: azohra/shell-linter@latest
        - name: Run ShellCheck
          uses: azohra/shell-linter@latest
          with:
            path: "./*.sh"
        - name: Step two make file executable
          run: chmod +x ./Create_files.sh ./amount_files_before.sh amount_files_after.sh cleanup_files.sh
        - name: Step three - Create files
          run: ./Create_files.sh
        - name: Step four - count files
          run: ./amount_files_before.sh
        - name: Step five - clean up files
          run: ./cleanup_files.sh
        - name: Step six - count after files
          run: ./amount_files_after.sh
    job2:
        name: secound job
        runs-on: windows-latest
        steps:
          - name: Step one - Check out code
            uses: actions/checkout@v2
          - name: Step two windows make file executable
            run: powershell.exe .\create-files.ps1
          - name: Step three Clean up files
            run: powershell.exe .\Cleanup-Files.ps1
          - name: Perform a Pester test from the .\create-files.ps1 file
            shell: pwsh
            run: |
              Invoke-Pester .\create-files.ps1 -Passthru
  